/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 3/23/2020
 ***********************************************************************************************/

#ifndef PNP_SCHEMA_TYPES_H
#define PNP_SCHEMA_TYPES_H

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @file pnp_schema_types.h
 * @brief PnP Schema Type Definition.
 */

/*------------------------ Type Definition for Telemetry Schema ----------------------------*/
/**
 * @brief Data type definition of the location telemetry.
 */
typedef struct pocsensor_location_tag
{
    double latitude;    /* distance from equator */
    double longitude;   /* istance from meridian */
} pocsensor_location;

/*------------------------ Type Definition for Property Schema ----------------------------*/
/**
 * @brief Data type definition of the settings property.
 */
typedef struct pocsensor_settings_tag
{
    double fanSpeed;    /* target fan speed to set */
    double voltage;     /* target voltage to set */

} pocsensor_settings;

/*---------------- Type Definition for Command Request and Response Schema -----------------*/
/**
 * @brief Data type definition of the updateFirmware command request.
 */
typedef struct pocsensor_update_firmware_request_tag
{
    char* firmware_uri;      /* the download uri for the new firmware */
    int firmware_version;    /* the new firmware version */
} pocsensor_update_firmware_request;

#ifdef __cplusplus
}
#endif

#endif // PNP_SCHEMA_TYPES_H
