/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 3/23/2020
 ***********************************************************************************************/

#ifndef POCSENSOR_INTERFACE_H
#define POCSENSOR_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "../serializer/pocsensor_serializer.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE pocsensor_create();

DIGITALTWIN_CLIENT_RESULT pocsensor_send_location_telemetry();

DIGITALTWIN_CLIENT_RESULT pocsensor_repoty_battery_remaining();

void pocsensor_close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

#ifdef __cplusplus
}
#endif

#endif  // POCSENSOR_INTERFACE_H
