/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 3/23/2020
 ***********************************************************************************************/

#ifndef POCDEVICE_IMPL
#define POCDEVICE_IMPL

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "../modellib/pnp_schema_types.h"

/*--------------- Telemetry Date Getter and Callback Function ------------------*/
void pocsensor_get_location(pocsensor_location * location);

/*------------- Property Data Getter and Callback Functions -------------------*/
double pocsensor_get_battery_remaining();
bool pocsensor_update_settings(pocsensor_settings *settings);

/*------------------------- Command Execution Functions -----------------------*/
bool pocsensor_update_firmware(pocsensor_update_firmware_request *update_firmware_request);

#ifdef __cplusplus
}
#endif

#endif // POCDEVICE_IMPL
