/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 3/23/2020
 ***********************************************************************************************/

#ifndef POCINTERFACE_INTERFACE_H
#define POCINTERFACE_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "../pnp_schema_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum POCINTERFACE_TELEMETRY_TAG
{
    pocinterface_location_TELEMETRY
} POCINTERFACE_TELEMETRY;

typedef enum POCINTERFACE_READONLY_PROPERTY_TAG
{
    pocsensor_BATTERYREMAINING_PROPERTY,
    pocinterface_settings_PROPERTY
} POCINTERFACE_PROPERTY;

// DigitalTwin interface name from service perspective.
static const char PocInterfaceInterfaceId[] = "urn:test:pocInterface:1";
static const char PocInterfaceInterfaceInstanceName[] = "pocInterface";

// Telemetry names for this interface.

static const char PocInterfaceInterface_LocationTelemetry[] = "location";

// Property names for this interface.

#define PocInterfaceInterface_BatteryRemainingProperty "battery_remaining"

#define PocInterfaceInterface_SettingsProperty "settings"

// Command names for this interface

#define PocInterfaceInterface_UpdateFirmwareCommand "updateFirmware"

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE PocInterfaceInterface_Create();

void PocInterfaceInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT PocInterfaceInterface_Telemetry_SendAll();

DIGITALTWIN_CLIENT_RESULT PocInterfaceInterface_Property_ReportAll();

DIGITALTWIN_CLIENT_RESULT PocInterfaceInterface_Property_ReportBatteryRemaining();

#ifdef __cplusplus
}
#endif

#endif  // POCINTERFACE_INTERFACE_H
