/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 3/23/2020
 ***********************************************************************************************/

#ifndef POCDEVICE_IMPL
#define POCDEVICE_IMPL

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "pnp_schema_types.h"

/**
* @brief Result of DigitalTwin command execution.
*/
typedef enum DIGITALTWIN_COMMAND_RESULT_TAG
{
    DIGITALTWIN_COMMAND_OK,
    DIGITALTWIN_COMMAND_TIMEOUT,
    DIGITALTWIN_COMMAND_ERROR
} DIGITALTWIN_COMMAND_RESULT;

/*--------------- Telemetry Date Getter and Callback Function ------------------*/
void pocsensor_get_location(pocinterface_location * location);

/*------------- Property Data Getter and Callback Functions -------------------*/
double pocsensor_get_battery_remaining();
bool pocsensor_get_settings(pocinterface_settings *settings);

/*------------------------- Command Execution Functions -----------------------*/
DIGITALTWIN_COMMAND_RESULT pocsensor_Command_UpdateFirmware(pocinterface_updatefirmware_request *updateFirmwareParams, bool* response, unsigned int* statusCode);

#ifdef __cplusplus
}
#endif

#endif // POCDEVICE_IMPL
