/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 3/23/2020
 *******************************************************************************************/

#include <string.h>
#include "pocDevice_impl.h"
#include "utilities/pocinterface_interface.h"

void pocsensor_get_location(pocinterface_location * location)
{
    double latitude = 20.0f + ((double)rand() / RAND_MAX) * 15.0f;
    double longitude = 10.0f + ((double)rand() / RAND_MAX) * 20.0f;
    location->latitude = latitude;
    location->longitude = longitude;
}

double pocsensor_get_battery_remaining()
{
    double remain = 100.0f + ((double)rand() / RAND_MAX) * 15.0f;
    return remain;
}

bool pocsensor_get_settings(pocinterface_settings *settings)
{
    printf("Set current fan speed to: %f", settings->fanSpeed);
    printf("Set current voltage to: %f", settings->voltage);

    // do somthing with the new settings ...

    return true;
}

DIGITALTWIN_COMMAND_RESULT pocsensor_Command_UpdateFirmware(pocinterface_updatefirmware_request *updateFirmwareParams, bool* response, unsigned int* statusCode)
{
    printf("Parameter: updateFirmwareParams->firmwareUri = %s", updateFirmwareParams->firmwareUri);
    printf("Parameter: updateFirmwareParams->firmwareVersion = %d", updateFirmwareParams->firmwareVersion);

    // do somthing to process the updateFirmware command ...

    *statusCode = 200;
    *response = true;

    printf("Device executed 'updateFirmware' command successfully");
    return DIGITALTWIN_COMMAND_OK;
}
